version: '3'
services:
  frontend_server:
    image: singahu/dataproject-front-react:0.0.1
    restart: "on-failure"
    ports:
      - 80:80
    networks:
      - data-service

  backend_server:
    image: singahu/dataproject-back-nodejs:0.0.1
    restart: "on-failure"
    ports:
      - 5001:5001
    networks:
      - data-service

networks:
  data-service:

